### PR TITLE
update core package dependency material-table to 1.69.0

### PR DESCRIPTION
**Pull request by alileza**
## Hey, I just made a Pull Request!

This update is needed to fix an issue if jspdf fileSaver issue https://github.com/MrRio/jsPDF/issues/2490. When the dependency configured to fetch directly from github, it caused a problem when npm install runs in infrastructure that unable to access github.com. 

This changes as the changelog of material-table shown did an update to jspdf 2.0.0 which don't rely on file-saver dependency anymore

jspdf changelog update: https://github.com/mbrn/material-table/compare/v1.68.0...v1.69.0#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R85

#### :heavy_check_mark: Checklist

- [x] All tests are passing `yarn test`
- [x] Screenshots attached (for UI changes)
- [x] Relevant documentation updated
- [x] Prettier run on changed files
- [x] Tests added for new functionality
- [x] Regression tests added for bug fixes

### CODE REVIEW

**Comment by freben** [comment]
Hi! Any particular reason this is a draft? Would be happy to merge

**Comment by freben** [comment]
also done in #2248 but that one forgot to check in yarn.lock

**Review by freben — APPROVED** [review]

**Comment by freben** [comment]
Ah shoot, that build error again - you may want to upgrade the yarn.lock version to 2.1.0 i think https://github.com/MrRio/jsPDF/issues/2846#issuecomment-686321689

**Comment by Rugvip** [comment]
Fixed in https://github.com/MrRio/jsPDF/commit/ab21994a6262bb14568c01d643e079fd197d8443#diff-b9cfc7f2cdf78a7f4b91a753d10865a2, so hopefully working in the next release

**Comment by alileza** [comment]
Hi @freben yeah I'm trying to figure out the issue with those e2e doesn't seem to work, I'd update the PR once jspdf fixes went through

**Comment by freben** [comment]
We could probably bump the resolved version in yarn.lock manually to 2.1.0, right? https://github.com/MrRio/jsPDF/releases/tag/v2%2C1%2C0

**Comment by freben** [comment]
Ah sorry, it's a fixed version dep :/

**Comment by alileza** [comment]
still the same error with version 2.1.0, I tested this locally, seems like `material-table@1.69.0` is a breaking change for backstage 😞

```

Error: Failed to compile.
/tmp/backstage-e2e-c2nTQC/test-app/node_modules/jspdf/dist/jspdf.umd.min.js
Critical dependency: the request of a dependency is an expression

/tmp/backstage-e2e-c2nTQC/test-app/node_modules/jspdf/dist/jspdf.umd.min.js
Critical dependency: the request of a dependency is an expression
```

**Comment by bresmith-wayfair** [comment]
👋    @alileza and I work together and are both trying to solve this issue so whichever PR works better works for us 😄

**Comment by bresmith-wayfair** [comment]
for more context, I tried the route suggested above and manually bumped the resolved versions in our own yarn.lock for our instance of backstage generated via the cli and we are able to build successfully, avoiding the FileSaver.js issue on our github deprived CI system, but apparently there is a breaking change and the UI does not render

**Comment by freben** [comment]
OK. When they cut a new release of material-table this should be easier to fix fully. I guess we wait a bit... They seem to have a somewhat frequent release cadence.

Or are you blocked to such a degree that we should even do something more drastic like downgrading far enough that the jspdf dependency is gone?

**Comment by bresmith-wayfair** [comment]
we are unblocking ourselves for now, but it would be great to get this fixed asap. I can imagine we are not the only ones experiencing this pain.

**Comment by marcuseide** [comment]
This is done in #2782

**Pull request closed without merging**
